[workspace]
resolver = "2"
members = ["crates/podic-core", "crates/podic-server", "crates/podic-mobile", "crates/podic-ohos"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
rusqlite = { version = "0.40", features = ["bundled"] }
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tower-http = { version = "0.6", features = ["fs", "cors"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
sha2 = "0.10"
flate2 = "1"
unicode-normalization = "0.1"

[profile.release]
strip = true
lto = true
