[package]
name = "podic-mobile"
version.workspace = true
edition.workspace = true

[lib]
name = "podic_mobile"
crate-type = ["cdylib", "staticlib"]

[dependencies]
podic-core = { path = "../podic-core" }
podic-server = { path = "../podic-server" }
jni = "0.21"
axum.workspace = true
tokio.workspace = true
